### ISSUE TITLE
error: failed to commit transaction (conflicting files)

### ISSUE THREAD

**Issue by karamhorane** [SteveStudios/SDesk#8]
error: failed to commit transaction (conflicting files)
lsb-release: /etc/lsb-release exists in filesystem
Errors occurred, no packages were upgraded.
 -> Failed to install layer, rolling up to next layer.error:error installing repo packages
resolving dependencies...

When try to install many software's they find conflict and the onlt solutution is to add --overwrite  /etc/lsb-release  which will alter all the file content and make it pure arch data

**Comment by stephencomputer** [comment]
Thanks for reporting this. I'll take a look.

**Comment by stephencomputer** [comment]
Looks like neofetch is deprecated anyway. Will remove it in the next release.

**Comment by stephencomputer** [comment]
New release coming out (hopefully) later today. Both neofetch and the release file are removed from it
